Task Markdown & Git
Repmvby/rsschool-cv pull request #1
Opened 2020-10-14 14:36 UTC by Repmvby

Add Readme.md file with link.
Add cv.md with Kuzmin Dzmitry cv.

2020-10-19 09:06 UTC, MedvedevaM requested changes

2020-10-19 09:06 UTC, MedvedevaM commented on cv.md
> +2. Contact info:</br>
`<br>` is used in html for breaking the line. I suppose it's not needed here and below. Please, correct me, if I'm wrong.

2020-10-19 09:06 UTC, MedvedevaM commented on cv.md
> +   - Bachelor's Degree in Social and Medical Psychology</br>
Please, remove `</br>`.

2020-10-19 09:06 UTC, MedvedevaM commented on cv.md
> +   - Middle school No 9, Brest, Belarus. Position: Educational psychologist.</br>
Please, remove `</br>`

2020-10-19 09:06 UTC, MedvedevaM commented on cv.md
> +   2017-2019</br>
Please, remove `</br>`

2020-10-19 13:51 UTC, Repmvby commented on cv.md
> +   2017-2019</br>
I think <br> needs here, because i иecause I wanted to make the date a separate line.

2020-10-19 13:57 UTC, Repmvby commented on cv.md
> +   - Bachelor's Degree in Social and Medical Psychology</br>
I think `br` needs here, because I wanted to make the date a separate line.

2020-10-19 17:41 UTC, MedvedevaM requested changes

2020-10-19 17:41 UTC, MedvedevaM commented on cv.md
> +   - Bachelor's Degree in Social and Medical Psychology</br>
But if to navigate to https://repmvby.github.io/rsschool-cv/cv  there is `</br>`  displayed instead of a separate line.

2020-10-19 17:41 UTC, MedvedevaM commented on cv.md
> +   2017-2019</br>
Same here.

2020-10-21 13:17 UTC, Repmvby commented on cv.md
> +   - Bachelor's Degree in Social and Medical Psychology</br>
fixed

2020-10-21 13:17 UTC, Repmvby commented on cv.md
> +   2017-2019</br>
fixed.

2020-11-10 12:20 UTC, merged